### ISSUE TITLE
No timeout for WebRTCVad?

### ISSUE THREAD

**Issue by daniele-athome** [rhasspy/rhasspy-remote-http-hermes#3]
I see [here](https://github.com/rhasspy/rhasspy-remote-http-hermes/blob/master/rhasspyremote_http_hermes/__init__.py#L164) that the code doesn't pass maxSeconds for setting up a timeout. I can see the comment where you state that... was that by choice? And if so, why?

P.S. the same happens in the pocketsphinx-hermes module

**Comment by synesthesiam** [comment]
Yes, this was by choice. Timeouts in Rhasspy 2.5 are handled now by the dialogue management service (like Snips). It will close the ASR session once the timeout has been reached and then start the next queued session.

I may add an option to override this for the case where you want to run Rhasspy 2.5 without the dialogue manager, though.

**Comment by daniele-athome** [comment]
Oh, I didn't notice the parameter. I'll use that then. Thanks!
